"""initial evidence-first schema"""

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

revision = "aafebf866348"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entities",
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("platform_identifiers", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_table(
        "memes",
        sa.Column("canonical_name", sa.String(length=200), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("usage_context", sa.Text(), nullable=False),
        sa.Column("origin_status", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("published_revision", sa.Integer(), nullable=False),
        sa.Column("merged_into_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merged_into_id"],
            ["memes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_memes_normalized_name"), "memes", ["normalized_name"], unique=False)
    op.create_index(op.f("ix_memes_status"), "memes", ["status"], unique=False)
    op.create_table(
        "aliases",
        sa.Column("meme_id", sa.String(length=36), nullable=False),
        sa.Column("normalized", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["meme_id"],
            ["memes.id"],
        ),
        sa.PrimaryKeyConstraint("meme_id", "normalized"),
    )
    op.create_index(op.f("ix_aliases_normalized"), "aliases", ["normalized"], unique=False)
    op.create_table(
        "events",
        sa.Column("meme_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("occurred_at_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("occurred_at_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_precision", sa.String(length=20), nullable=False),
        sa.Column("time_basis", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["meme_id"],
            ["memes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_meme_id"), "events", ["meme_id"], unique=False)
    op.create_table(
        "revisions",
        sa.Column("meme_id", sa.String(length=36), nullable=False),
        sa.Column("based_on_revision", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("review_reason", sa.Text(), nullable=True),
        sa.Column("reviewer", sa.String(length=100), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["meme_id"],
            ["memes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_revisions_meme_id"), "revisions", ["meme_id"], unique=False)
    op.create_index(op.f("ix_revisions_status"), "revisions", ["status"], unique=False)
    op.create_table(
        "sources",
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("platform_item_id", sa.String(length=100), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("submitted_url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("author_entity_id", sa.String(length=36), nullable=True),
        sa.Column("platform_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("availability", sa.String(length=32), nullable=False),
        sa.Column("metadata_key", sa.Text(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_entity_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "platform_item_id"),
    )
    op.create_index(op.f("ix_sources_platform"), "sources", ["platform"], unique=False)
    op.create_index(
        op.f("ix_sources_platform_published_at"), "sources", ["platform_published_at"], unique=False
    )
    op.create_table(
        "evidence",
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("locator", sa.JSON(), nullable=False),
        sa.Column("artifact_key", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("artifact_hash", sa.String(length=64), nullable=False),
        sa.Column("extraction_provenance", sa.JSON(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("retracted", sa.Boolean(), nullable=False),
        sa.Column("supersedes_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["evidence.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidence_source_id"), "evidence", ["source_id"], unique=False)
    op.create_table(
        "relations",
        sa.Column("meme_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("predicate", sa.String(length=40), nullable=False),
        sa.Column("to_meme_id", sa.String(length=36), nullable=True),
        sa.Column("to_source_id", sa.String(length=36), nullable=True),
        sa.Column("to_entity_id", sa.String(length=36), nullable=True),
        sa.Column("assertion_status", sa.String(length=24), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(CASE WHEN to_meme_id IS NULL THEN 0 ELSE 1 END + CASE WHEN to_source_id IS NULL THEN 0 ELSE 1 END + CASE WHEN to_entity_id IS NULL THEN 0 ELSE 1 END) = 1",
            name="one_relation_target",
        ),
        sa.ForeignKeyConstraint(
            ["meme_id"],
            ["memes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_meme_id"],
            ["memes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_relations_meme_id"), "relations", ["meme_id"], unique=False)
    op.create_index(op.f("ix_relations_to_meme_id"), "relations", ["to_meme_id"], unique=False)
    op.create_table(
        "chunks",
        sa.Column("meme_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.Column("offset", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding_model", sa.Text(), nullable=True),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1024).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
        ),
        sa.ForeignKeyConstraint(
            ["meme_id"],
            ["memes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("meme_id", "revision", "evidence_id", "offset"),
    )
    op.create_index(op.f("ix_chunks_evidence_id"), "chunks", ["evidence_id"], unique=False)
    op.create_index(op.f("ix_chunks_meme_id"), "chunks", ["meme_id"], unique=False)
    op.create_table(
        "evidence_links",
        sa.Column("meme_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=True),
        sa.Column("relation_id", sa.String(length=36), nullable=True),
        sa.Column("claim_key", sa.String(length=100), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("stance", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
        ),
        sa.ForeignKeyConstraint(
            ["meme_id"],
            ["memes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["relation_id"],
            ["relations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidence_links_evidence_id"), "evidence_links", ["evidence_id"], unique=False)
    op.create_index(op.f("ix_evidence_links_meme_id"), "evidence_links", ["meme_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidence_links_meme_id"), table_name="evidence_links")
    op.drop_index(op.f("ix_evidence_links_evidence_id"), table_name="evidence_links")
    op.drop_table("evidence_links")
    op.drop_index(op.f("ix_chunks_meme_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_evidence_id"), table_name="chunks")
    op.drop_table("chunks")
    op.drop_index(op.f("ix_relations_to_meme_id"), table_name="relations")
    op.drop_index(op.f("ix_relations_meme_id"), table_name="relations")
    op.drop_table("relations")
    op.drop_index(op.f("ix_evidence_source_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_sources_platform_published_at"), table_name="sources")
    op.drop_index(op.f("ix_sources_platform"), table_name="sources")
    op.drop_table("sources")
    op.drop_index(op.f("ix_revisions_status"), table_name="revisions")
    op.drop_index(op.f("ix_revisions_meme_id"), table_name="revisions")
    op.drop_table("revisions")
    op.drop_index(op.f("ix_events_meme_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_aliases_normalized"), table_name="aliases")
    op.drop_table("aliases")
    op.drop_index(op.f("ix_memes_status"), table_name="memes")
    op.drop_index(op.f("ix_memes_normalized_name"), table_name="memes")
    op.drop_table("memes")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("entities")
    # ### end Alembic commands ###
