/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Url */
        post: operations["submit_url_v1_submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_v1_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/{source_id}/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Material */
        post: operations["material_v1_sources__source_id__materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/{source_id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Media */
        post: operations["media_v1_sources__source_id__media_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source Detail */
        get: operations["source_detail_v1_sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence Detail */
        get: operations["evidence_detail_v1_evidence__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence/{evidence_id}/artifact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence Artifact */
        get: operations["evidence_artifact_v1_evidence__evidence_id__artifact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memes/{meme_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meme Detail */
        get: operations["meme_detail_v1_memes__meme_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memes/{meme_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timeline */
        get: operations["timeline_v1_memes__meme_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memes/{meme_id}/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Relations */
        get: operations["relations_v1_memes__meme_id__relations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Api */
        post: operations["search_api_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answers Api */
        post: operations["answers_api_v1_answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reviews */
        get: operations["reviews_v1_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Source */
        get: operations["review_source_v1_reviews_sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Evidence */
        get: operations["review_evidence_v1_reviews_evidence__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/sources/{source_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Source */
        post: operations["refresh_source_v1_reviews_sources__source_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draft */
        post: operations["draft_v1_reviews_drafts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/{revision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit Draft */
        put: operations["edit_draft_v1_reviews__revision_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/{revision_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decision */
        post: operations["decision_v1_reviews__revision_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/memes/{meme_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_v1_reviews_memes__meme_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/memes/{meme_id}/retract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retract */
        post: operations["retract_v1_reviews_memes__meme_id__retract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/evidence/{evidence_id}/retract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retract Evidence */
        post: operations["retract_evidence_v1_reviews_evidence__evidence_id__retract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/memes/{meme_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge */
        post: operations["merge_v1_reviews_memes__meme_id__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Entity */
        post: operations["add_entity_v1_reviews_entities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reindex */
        post: operations["reindex_v1_reviews_reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerClaim */
        AnswerClaim: {
            /** Key */
            key: string;
            /** Statement */
            statement: string;
            /** Stance */
            stance: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Meme Id */
            meme_id: string;
            /** Meme Name */
            meme_name: string;
            /** Origin Status */
            origin_status: string;
        };
        /** AnswerOut */
        AnswerOut: {
            /** Answer */
            answer: string;
            /** Claims */
            claims: components["schemas"]["AnswerClaim"][];
            /** Citations */
            citations: components["schemas"]["CitationOut"][];
            /** Uncertainties */
            uncertainties: string[];
            /** Mode */
            mode: string;
            /** Retrieval Version */
            retrieval_version: string;
            /** Channels */
            channels: string[];
            /** Degraded */
            degraded: string[];
        };
        /** Body_media_v1_sources__source_id__media_post */
        Body_media_v1_sources__source_id__media_post: {
            /** File */
            file: string;
        };
        /** CitationOut */
        CitationOut: {
            /** Evidence Id */
            evidence_id: string;
            /** Source Id */
            source_id: string;
            /** Url */
            url: string;
            /** Text */
            text: string;
            /** Locator */
            locator: {
                [key: string]: unknown;
            };
            /** Content Hash */
            content_hash: string;
            /** Meme Revision */
            meme_revision: number;
            /** Published At */
            published_at: string | null;
        };
        /** Claim */
        Claim: {
            /**
             * Key
             * @enum {string}
             */
            key: "definition" | "usage_context" | "origin" | "alias";
            /** Statement */
            statement: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /**
             * Stance
             * @default supports
             * @enum {string}
             */
            stance: "supports" | "contradicts";
        };
        /** ClaimOut */
        ClaimOut: {
            /** Key */
            key: string;
            /** Statement */
            statement: string;
            /** Stance */
            stance: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** EntityInput */
        EntityInput: {
            /** Entity Type */
            entity_type: string;
            /** Name */
            name: string;
            /** Aliases */
            aliases?: string[];
            /** Platform Identifiers */
            platform_identifiers?: {
                [key: string]: unknown;
            };
        };
        /** EventInput */
        EventInput: {
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "observed_use" | "spread" | "remix" | "origin_claim";
            /** Description */
            description: string;
            /** Occurred At Start */
            occurred_at_start?: string | null;
            /** Occurred At End */
            occurred_at_end?: string | null;
            /**
             * Time Precision
             * @default unknown
             * @enum {string}
             */
            time_precision: "unknown" | "year" | "month" | "day" | "second";
            /** Time Basis */
            time_basis: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: string;
            /** Event Type */
            event_type: string;
            /** Description */
            description: string;
            /** Occurred At Start */
            occurred_at_start: string | null;
            /** Occurred At End */
            occurred_at_end: string | null;
            /** Time Precision */
            time_precision: string;
            /** Time Basis */
            time_basis: string;
            /** Evidence Ids */
            evidence_ids?: string[];
        };
        /** EvidenceOut */
        EvidenceOut: {
            /** Id */
            id: string;
            /** Source Id */
            source_id: string;
            /** Kind */
            kind: string;
            /** Text */
            text: string;
            /** Locator */
            locator: {
                [key: string]: unknown;
            };
            /** Verified */
            verified: boolean;
            /** Retracted */
            retracted: boolean;
            /** Content Hash */
            content_hash: string;
            /** Artifact Hash */
            artifact_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            source?: components["schemas"]["SourceOut"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Material */
        Material: {
            /** Text */
            text: string;
            /**
             * Kind
             * @default manual
             * @enum {string}
             */
            kind: "manual" | "subtitle" | "asr" | "ocr" | "metadata";
            /** Locator */
            locator?: {
                [key: string]: unknown;
            };
            /** Supersedes Id */
            supersedes_id?: string | null;
        };
        /** MemeDraft */
        MemeDraft: {
            /** Canonical Name */
            canonical_name: string;
            /** Aliases */
            aliases?: string[];
            /**
             * Definition
             * @default
             */
            definition: string;
            /**
             * Usage Context
             * @default
             */
            usage_context: string;
            /**
             * Origin Status
             * @default unknown
             * @enum {string}
             */
            origin_status: "unknown" | "supported" | "disputed";
            /** Claims */
            claims?: components["schemas"]["Claim"][];
            /** Events */
            events?: components["schemas"]["EventInput"][];
            /** Relations */
            relations?: components["schemas"]["RelationInput"][];
        };
        /** MemeOut */
        MemeOut: {
            /** Id */
            id: string;
            /** Canonical Name */
            canonical_name: string;
            /** Aliases */
            aliases: string[];
            /** Definition */
            definition: string;
            /** Usage Context */
            usage_context: string;
            /** Origin Status */
            origin_status: string;
            /** Published Revision */
            published_revision: number;
            /** Evidence */
            evidence: components["schemas"]["EvidenceOut"][];
            /** Claims */
            claims: components["schemas"]["ClaimOut"][];
            /** Events */
            events: components["schemas"]["EventOut"][];
            /** Relations */
            relations: components["schemas"]["RelationOut"][];
            /**
             * Exact Match
             * @default false
             */
            exact_match: boolean;
            /** Matches */
            matches?: {
                [key: string]: unknown;
            }[];
        };
        /** MergeRequest */
        MergeRequest: {
            /** Reason */
            reason: string;
            /** Target Id */
            target_id: string;
        };
        /** Reason */
        Reason: {
            /** Reason */
            reason: string;
        };
        /** RelationInput */
        RelationInput: {
            /**
             * Predicate
             * @enum {string}
             */
            predicate: "derived_from" | "variant_of" | "claimed_origin" | "mentions" | "documented_in";
            /**
             * Target Type
             * @enum {string}
             */
            target_type: "meme" | "source" | "entity";
            /** Target Id */
            target_id: string;
            /**
             * Assertion Status
             * @default supported
             * @enum {string}
             */
            assertion_status: "supported" | "disputed";
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** RelationOut */
        RelationOut: {
            /** Id */
            id: string;
            /** Predicate */
            predicate: string;
            /** To Meme Id */
            to_meme_id: string | null;
            /** To Source Id */
            to_source_id: string | null;
            /** To Entity Id */
            to_entity_id: string | null;
            /** Assertion Status */
            assertion_status: string;
            /** Evidence Ids */
            evidence_ids?: string[];
        };
        /** ReviewAction */
        ReviewAction: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject";
            /** Reason */
            reason: string;
            /** Verified Evidence Ids */
            verified_evidence_ids?: string[];
        };
        /** SearchOut */
        SearchOut: {
            /** Items */
            items: components["schemas"]["MemeOut"][];
            /** Total */
            total: number;
            /** Channels */
            channels: string[];
            /** Degraded */
            degraded: string[];
            /** Query */
            query: string;
            /**
             * Total Is Candidate Count
             * @default false
             */
            total_is_candidate_count: boolean;
        };
        /** SearchRequest */
        SearchRequest: {
            /**
             * Query
             * @default
             */
            query: string;
            /** Platform */
            platform?: ("bilibili" | "douyin") | null;
            /** Published After */
            published_after?: string | null;
            /** Published Before */
            published_before?: string | null;
            /**
             * Limit
             * @default 20
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** SourceOut */
        SourceOut: {
            /** Id */
            id: string;
            /** Platform */
            platform: string;
            /** Platform Item Id */
            platform_item_id: string;
            /** Canonical Url */
            canonical_url: string;
            /** Title */
            title: string;
            /** Platform Published At */
            platform_published_at: string | null;
            /** Availability */
            availability: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Submission */
        Submission: {
            /** Url */
            url: string;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stats_v1_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    submit_url_v1_submissions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Submission"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_v1_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    material_v1_sources__source_id__materials_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Material"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    media_v1_sources__source_id__media_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_media_v1_sources__source_id__media_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_detail_v1_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_detail_v1_evidence__evidence_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_artifact_v1_evidence__evidence_id__artifact_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meme_detail_v1_memes__meme_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meme_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_v1_memes__meme_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meme_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    relations_v1_memes__meme_id__relations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meme_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answers_api_v1_answers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reviews_v1_reviews_get: {
        parameters: {
            query?: {
                status?: string;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_source_v1_reviews_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_evidence_v1_reviews_evidence__evidence_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_source_v1_reviews_sources__source_id__refresh_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_v1_reviews_drafts_post: {
        parameters: {
            query?: {
                meme_id?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemeDraft"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_draft_v1_reviews__revision_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemeDraft"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decision_v1_reviews__revision_id__decision_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_v1_reviews_memes__meme_id__history_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                meme_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retract_v1_reviews_memes__meme_id__retract_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                meme_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reason"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retract_evidence_v1_reviews_evidence__evidence_id__retract_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reason"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_v1_reviews_memes__meme_id__merge_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                meme_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_entity_v1_reviews_entities_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_v1_reviews_reindex_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
